services:
  postgres:
    image: postgres:16
    container_name: app_postgres
    environment:
      POSTGRES_USER: ${DATABASE__USER}
      POSTGRES_PASSWORD: ${DATABASE__PASSWORD}
      POSTGRES_DB: ${DATABASE__DB}
    ports:
      - "${DATABASE__PORT}:${DATABASE__PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE__USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
